### ISSUE TITLE
Docker-101: Tutorial - Node Application does not open on port 3000.

### ISSUE THREAD

**Issue by rajBopche** [dockersamples/101-tutorial#20]
I was following the **Docker 101 tutorial** on the **Docker Playground** and reached **Starting an App Container** checkpoint in **Our Application section**. 

<img width="998" alt="Screenshot 2020-05-14 at 8 24 20 PM" src="https://user-images.githubusercontent.com/42612104/81949922-ff072680-9620-11ea-89be-0817160daeb0.png">

As directed I hit the `docker run -dp 3000:3000 docker-101` command and waited for 3000 badge to appear on PWD interface, but nothing happened the badge never appeared. 

Instead, a very long ambiguous number appeared after the command on PWD in Docker Playground.

<img width="1103" alt="Screenshot 2020-05-14 at 8 14 22 PM" src="https://user-images.githubusercontent.com/42612104/81948577-83f14080-961f-11ea-99c2-45d1f288496b.png">

I even tried manually to access localhost, but all in vain.

<img width="1054" alt="Screenshot 2020-05-14 at 8 15 53 PM" src="https://user-images.githubusercontent.com/42612104/81948763-b864fc80-961f-11ea-9168-75de360b9783.png">

MacBook Pro Specs: 

1. MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2. Processor 2.3Ghz Dual-Core Intel Core i5
3. Memory 8 GB 2133 Mhz LPDDR3

OS: 

1. macOS Catalina
2. version: 10.15.3

Google Chrome: 

1. version:  81.0.4044.138 (Official Build) (64-bit)

I was never able to access the Node **To-Do List Application** running on port 3000.

**Comment by eoiwes** [comment]
Same for me

**Comment by KaushikPathak90** [comment]
> I was following the **Docker 101 tutorial** on the **Docker Playground** and reached **Starting an App Container** checkpoint in **Our Application section**.
> 
> <img alt="Screenshot 2020-05-14 at 8 24 20 PM" width="998" src="https://user-images.githubusercontent.com/42612104/81949922-ff072680-9620-11ea-89be-0817160daeb0.png">
> 
> As directed I hit the `docker run -dp 3000:3000 docker-101` command and waited for 3000 badge to appear on PWD interface, but nothing happened the badge never appeared.
> 
> Instead, a very long ambiguous number appeared after the command on PWD in Docker Playground.
> 
> <img alt="Screenshot 2020-05-14 at 8 14 22 PM" width="1103" src="https://user-images.githubusercontent.com/42612104/81948577-83f14080-961f-11ea-99c2-45d1f288496b.png">
> 
> I even tried manually to access localhost, but all in vain.
> 
> <img alt="Screenshot 2020-05-14 at 8 15 53 PM" width="1054" src="https://user-images.githubusercontent.com/42612104/81948763-b864fc80-961f-11ea-9168-75de360b9783.png">
> 
> MacBook Pro Specs:
> 
> 1. MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
> 2. Processor 2.3Ghz Dual-Core Intel Core i5
> 3. Memory 8 GB 2133 Mhz LPDDR3
> 
> OS:
> 
> 1. macOS Catalina
> 2. version: 10.15.3
> 
> Google Chrome:
> 
> 1. version:  81.0.4044.138 (Official Build) (64-bit)
> 
> I was never able to access the Node **To-Do List Application** running on port 3000.

"waited for 3000 badge to appear on PWD interface" -> Appeared. Clicked new tab opened but no list output(app).
Tried using diff browser Chrome and Firefox to check if Extensions were an issue but same result.

**Comment by KaushikPathak90** [comment]
Checked now..
Blank page opening with Title: Todo App

**Comment by 4slan** [comment]
The problem persists. Running container in "attached" mode shows this output:
```
$ docker run -p 3000:3000 docker-101
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/app/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by SNikhill** [comment]
> Checked now..
> Blank page opening with Title: Todo App

Greetings,
I know, my reply is too late but, if you still try to do what you did earlier and still see a blank page with the Todo App title. 
Can I please see the output in your browser console (like, open it up by Right Clicking and Inspect)?

Regards
SNikhill

**Comment by 4slan** [comment]
Hi @SNikhill!

There is no more error.

Best regards.
<img width="1680" alt="docker101" src="https://user-images.githubusercontent.com/22397481/106516025-c7098180-64d6-11eb-9293-ebf4cdfd4f94.png">

**Comment by SNikhill** [comment]
Greetings,
Thank you for replying. Good to know that no errors exist. :)

Regards
SNikhill

**Comment by ofaurax** [comment]
> 
> 
> The problem persists. Running container in "attached" mode shows this output:
> 
> ```
> $ docker run -p 3000:3000 docker-101
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '/app/src/index.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> ```

Same problem here and now
